### ISSUE TITLE
I would like the README to contains the heading to include `coverage`, supported `python version`

### ISSUE THREAD

**Issue by johnklee** [johnklee/fpu#19]
Take [`tqdm`](https://github.com/tqdm/tqdm) for example:

![demo](https://i.ibb.co/DKPVFx0/5.png)

**Comment by wkCircle** [comment]
From last PR #59, there are things undone.

Issues: 

1. coveralls requires `secrets.COVERALLS_REPO_TOKEN` (as seen in `ci-build.yml`). Since I have no permission to set up the repo secrets, the owner @johnklee needs to set this secret up following [Coveralls Official Tutorial](https://docs.coveralls.io/).

2. the README's current coveralls badge link connects to `wkCircle/fpu/badge.svg?branch=19-badges`, @johnklee needs to change it to `johnklee/fpu/badge.svg?branch=master`.

**Comment by johnklee** [comment]
Hi @wkCircle ,

Thanks for the great help on this issue. I will look into below item you pointed out in this [comment](https://github.com/johnklee/fpu/issues/19#issuecomment-1761265852).
